### ISSUE TITLE
start script of scalatra-atmosphere-embedded does not work

### ISSUE THREAD

**Issue by takezoe** [scalatra/scalatra-website-examples#31]
We can generate start script by hitting `./sbt stage`, but the generated script causes a following exception:

```
org.fusesource.scalate.TemplateException: Template file extension missing. Cannot determine which template processor to use.
        at org.fusesource.scalate.TemplateEngine.generator(TemplateEngine.scala:911)
        at org.fusesource.scalate.TemplateEngine.compileAndLoad(TemplateEngine.scala:800)
        at org.fusesource.scalate.TemplateEngine.compileAndLoadEntry(TemplateEngine.scala:745)

        at org.fusesource.scalate.TemplateEngine.liftedTree1$1(TemplateEngine.scala:446)
        at org.fusesource.scalate.TemplateEngine.load(TemplateEngine.scala:440)
        at org.fusesource.scalate.TemplateEngine.load(TemplateEngine.scala:495)
        at org.fusesource.scalate.TemplateEngine.layout(TemplateEngine.scala:565)
        at org.fusesource.scalate.TemplateEngine.layout(TemplateEngine.scala:634)
        at org.scalatra.scalate.ScalateSupport$class.layoutTemplateAs(ScalateSupport.scala:257)
        at org.scalatra.example.atmosphere.ChatController.layoutTemplateAs(ChatController.scala:18)
        at org.scalatra.scalate.ScalateSupport$class.ssp(ScalateSupport.scala:230)
        at org.scalatra.example.atmosphere.ChatController.ssp(ChatController.scala:18)
        at org.scalatra.example.atmosphere.ChatController$$anonfun$2.apply(ChatController.scala:27)
        at org.scalatra.example.atmosphere.ChatController$$anonfun$2.apply(ChatController.scala:25)
        at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$liftAction(ScalatraBase.scala:285)
        at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:279)
        at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:279)
        at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:189)
        at org.scalatra.example.atmosphere.ChatController.withRouteMultiParams(ChatController.scala:18)
        at org.scalatra.ScalatraBase$class.invoke(ScalatraBase.scala:278)
        at org.scalatra.example.atmosphere.ChatController.org$scalatra$json$JsonSupport$$super$invoke(ChatController.scala:18)
```

**Comment by magnolia-k** [comment]
It is fixed with the following PR

https://github.com/scalatra/scalatra-website-examples/pull/67

I updated the sbt command to the latest version

**Comment by takezoe** [comment]
@magnolia-k Thanks a lot!
