### ISSUE TITLE
Swagger-example: CORS issue in swagger-ui is back with scalatra v2.6.5

### ISSUE THREAD

**Issue by cdagraca** [scalatra/scalatra-website-examples#75]
Previously reported, and fixed in https://github.com/scalatra/scalatra-website-examples/issues/40, but is back.

Reproduce the problem:

Run the swagger-example as documented

- Download and open swagger-ui as described in their documentation http://swagger.io/docs/swagger-tools/#swagger-ui-documentation-29 or use http://petstore.swagger.io/
Enter http://localhost:8080/api-docs/swagger.json into the input field and hit "Explore"

Expected:

- Swagger-UI shows the api

Result:

- Font gets red and dev console shows CORS errors

Additional info:

- Pinning `ScalatraVersion` to `2.6.4` or lower resolves the issue
- Running with `2.6.5` produces dependency compatibility warnings and a non-fatal runtime error

Warnings: 
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
```
[warn] 	* org.scala-lang.modules:scala-xml_2.12:1.1.0 is selected over 1.0.6
[warn] 	    +- org.json4s:json4s-xml_2.12:3.6.3                   (depends on 1.1.0)
[warn] 	    +- org.scalatra:scalatra_2.12:2.6.5                   (depends on 1.0.6)
[warn] 	    +- org.scala-lang:scala-compiler:2.12.4               (depends on 1.0.6)
[warn] 	    +- org.json4s:json4s-core_2.12:3.5.3                  (depends on 1.0.6)
[warn] 	    +- org.scalatra.scalate:scalate-util_2.12:1.8.0       (depends on 1.0.6)
[warn] 	* org.json4s:json4s-core_2.12:3.6.3 is selected over 3.5.3
[warn] 	    +- org.json4s:json4s-xml_2.12:3.6.3                   (depends on 3.6.3)
[warn] 	    +- org.scalatra:scalatra-json_2.12:2.6.5              (depends on 3.6.3)
[warn] 	    +- org.json4s:json4s-native_2.12:3.5.3                (depends on 3.5.3)
[warn] 	* org.json4s:json4s-scalap_2.12:3.6.3 is selected over 3.5.3
[warn] 	    +- org.json4s:json4s-core_2.12:3.6.3                  (depends on 3.6.3)
[warn] 	    +- org.json4s:json4s-core_2.12:3.5.3                  (depends on 3.5.3)
[warn] 	* org.json4s:json4s-ast_2.12:3.6.3 is selected over 3.5.3
[warn] 	    +- org.json4s:json4s-core_2.12:3.6.3                  (depends on 3.6.3)
[warn] 	    +- org.json4s:json4s-core_2.12:3.5.3                  (depends on 3.5.3)
```

Runtime error:
```
2019-10-04 10:29:57.003:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@2471cca7{/,file:///Users/catherine/workspace/scalatra-website-examples/2.6/swagger-example/target/webapp/,UNAVAILABLE}{file:///Users/catherine/workspace/scalatra-website-examples/2.6/swagger-example/target/webapp/}
java.lang.RuntimeException: Error scanning entry module-info.class from jar file:///Users/catherine/workspace/scalatra-website-examples/2.6/swagger-example/target/webapp/WEB-INF/lib/joda-convert-2.1.1.jar
	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:891)
	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:837)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:159)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:462)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
	at java.lang.Thread.run(Thread.java:748)
Caused by:
java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:959)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:940)
	at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:887)
	at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:837)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:159)
	at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:462)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
	at java.lang.Thread.run(Thread.java:748)
2019-10-04 10:29:57.026:INFO:oejs.AbstractConnector:main: Started ServerConnector@4883b407{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2019-10-04 10:29:57.027:INFO:oejs.Server:main: Started @1315ms
```

**Comment by cdagraca** [comment]
More info:

Explicitly updating json4s-native to `3.6.3` gets rid of all but the first eviction warning.

Upgrading `sbt.version` to `1.2.8` resolved both the eviction warnings and the joda error, but throws an exception when called from swagger-ui:
```
2019-10-04 10:49:54.456:INFO:oejs.Server:main: Started @2203ms
java.lang.NoSuchMethodError: org.json4s.JsonDSL$.seq2jvalue(Lscala/collection/Traversable;Lscala/Function1;)Lorg/json4s/JsonAST$JArray;
	at org.scalatra.swagger.SwaggerBaseBase$$anonfun$$nestedInanonfun$renderSwagger2$13$1.$anonfun$applyOrElse$7(SwaggerBase.scala:158)
	at org.json4s.JsonDSL.pair2jvalue(JsonDSL.scala:82)
	at org.json4s.JsonDSL.pair2jvalue$(JsonDSL.scala:82)
	at org.json4s.JsonDSL$.pair2jvalue(JsonDSL.scala:64)
	at org.scalatra.swagger.SwaggerBaseBase$$anonfun$$nestedInanonfun$renderSwagger2$13$1.$anonfun$applyOrElse$1(SwaggerBase.scala:158)
	at scala.collection.immutable.List.map(List.scala:283)
	at org.scalatra.swagger.SwaggerBaseBase$$anonfun$$nestedInanonfun$renderSwagger2$13$1.applyOrElse(SwaggerBase.scala:153)
	at scala.collection.immutable.List.collect(List.scala:305)
	at org.scalatra.swagger.SwaggerBaseBase.$anonfun$renderSwagger2$13(SwaggerBase.scala:151)
	at scala.collection.immutable.List.flatMap(List.scala:335)
	at org.scalatra.swagger.SwaggerBaseBase.renderSwagger2(SwaggerBase.scala:149)
	at org.scalatra.swagger.SwaggerBaseBase.renderSwagger2$(SwaggerBase.scala:135)
	at org.scalatra.example.swagger.ResourcesApp.renderSwagger2(FlowersSwagger.scala:7)
	at org.scalatra.swagger.SwaggerBaseBase.$anonfun$initialize$1(SwaggerBase.scala:54)
	at org.scalatra.ScalatraBase.liftAction(ScalatraBase.scala:280)
	at org.scalatra.ScalatraBase.$anonfun$invoke$1(ScalatraBase.scala:274)
	at org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:183)
	at org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:169)
	at org.scalatra.example.swagger.ResourcesApp.withRouteMultiParams(FlowersSwagger.scala:7)
	at org.scalatra.ScalatraBase.invoke(ScalatraBase.scala:273)
	at org.scalatra.ScalatraBase.invoke$(ScalatraBase.scala:272)
	at org.scalatra.example.swagger.ResourcesApp.org$scalatra$json$JsonSupport$$super$invoke(FlowersSwagger.scala:7)
	at org.scalatra.json.JsonSupport.$anonfun$invoke$1(JsonSupport.scala:90)
	at org.scalatra.ApiFormats.withRouteMultiParams(ApiFormats.scala:183)
	at org.scalatra.ApiFormats.withRouteMultiParams$(ApiFormats.scala:169)
	at org.scalatra.example.swagger.ResourcesApp.withRouteMultiParams(FlowersSwagger.scala:7)
	at org.scalatra.json.JsonSupport.invoke(JsonSupport.scala:84)
	at org.scalatra.json.JsonSupport.invoke$(JsonSupport.scala:83)
	at org.scalatra.example.swagger.ResourcesApp.invoke(FlowersSwagger.scala:7)
	at org.scalatra.ScalatraBase.$anonfun$runRoutes$3(ScalatraBase.scala:248)
	at scala.Option.flatMap(Option.scala:171)
	at org.scalatra.ScalatraBase.$anonfun$runRoutes$1(ScalatraBase.scala:246)
	at scala.collection.immutable.Stream.flatMap(Stream.scala:486)
	at org.scalatra.ScalatraBase.runRoutes(ScalatraBase.scala:245)
	at org.scalatra.ScalatraBase.runRoutes$(ScalatraBase.scala:243)
	at org.scalatra.example.swagger.ResourcesApp.runRoutes(FlowersSwagger.scala:7)
	at org.scalatra.ScalatraBase.runActions$1(ScalatraBase.scala:169)
	at org.scalatra.ScalatraBase.$anonfun$executeRoutes$6(ScalatraBase.scala:181)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at org.scalatra.ScalatraBase.cradleHalt(ScalatraBase.scala:199)
	at org.scalatra.ScalatraBase.executeRoutes(ScalatraBase.scala:181)
	at org.scalatra.ScalatraBase.executeRoutes$(ScalatraBase.scala:150)
	at org.scalatra.example.swagger.ResourcesApp.executeRoutes(FlowersSwagger.scala:7)
	at org.scalatra.ScalatraBase.$anonfun$handle$1(ScalatraBase.scala:123)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope.withResponse(DynamicScope.scala:79)
	at org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:77)
	at org.scalatra.example.swagger.ResourcesApp.withResponse(FlowersSwagger.scala:7)
	at org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:59)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
	at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
	at org.scalatra.example.swagger.ResourcesApp.withRequest(FlowersSwagger.scala:7)
	at org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:58)
	at org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:56)
	at org.scalatra.example.swagger.ResourcesApp.withRequestResponse(FlowersSwagger.scala:7)
	at org.scalatra.ScalatraBase.handle(ScalatraBase.scala:123)
	at org.scalatra.ScalatraBase.handle$(ScalatraBase.scala:119)
	at org.scalatra.example.swagger.ResourcesApp.org$scalatra$servlet$ServletBase$$super$handle(FlowersSwagger.scala:7)
	at org.scalatra.servlet.ServletBase.handle(ServletBase.scala:53)
	at org.scalatra.servlet.ServletBase.handle$(ServletBase.scala:46)
	at org.scalatra.example.swagger.ResourcesApp.org$scalatra$CorsSupport$$super$handle(FlowersSwagger.scala:7)
	at org.scalatra.CorsSupport.$anonfun$handle$1(CORSSupport.scala:219)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope.withResponse(DynamicScope.scala:79)
	at org.scalatra.DynamicScope.withResponse$(DynamicScope.scala:77)
	at org.scalatra.example.swagger.ResourcesApp.withResponse(FlowersSwagger.scala:7)
	at org.scalatra.DynamicScope.$anonfun$withRequestResponse$1(DynamicScope.scala:59)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.scalatra.DynamicScope.withRequest(DynamicScope.scala:70)
	at org.scalatra.DynamicScope.withRequest$(DynamicScope.scala:68)
	at org.scalatra.example.swagger.ResourcesApp.withRequest(FlowersSwagger.scala:7)
	at org.scalatra.DynamicScope.withRequestResponse(DynamicScope.scala:58)
	at org.scalatra.DynamicScope.withRequestResponse$(DynamicScope.scala:56)
	at org.scalatra.example.swagger.ResourcesApp.withRequestResponse(FlowersSwagger.scala:7)
	at org.scalatra.CorsSupport.handle(CORSSupport.scala:209)
	at org.scalatra.CorsSupport.handle$(CORSSupport.scala:206)
	at org.scalatra.example.swagger.ResourcesApp.handle(FlowersSwagger.scala:7)
	at org.scalatra.ScalatraServlet.service(ScalatraServlet.scala:65)
	at org.scalatra.ScalatraServlet.service$(ScalatraServlet.scala:64)
	at org.scalatra.example.swagger.ResourcesApp.service(FlowersSwagger.scala:7)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:833)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
	at java.lang.Thread.run(Thread.java:748)
```
The error is related to this change in json4s, present in `v3.6.*` and higher: https://github.com/json4s/json4s/commit/14d15155abbff808785a815aa21408ca52ff731d, but as scalatra is build with version 3.6.3 I can't see any reason for it to be incompatible.
